### ISSUE TITLE
How to pass state-object (FSMContext) with context apscheduler-di. It's all in aiogram2

### ISSUE THREAD

**Issue by tsy-pavel** [GLEF1X/apscheduler-di#6]
Hi. I need some help. I am using aiogram2 + Redis + Apcheduler (RedisJobStore). I need to pass a state object belonging to the FSMContext class to the function that is called by the task. (I need to set the next state (await state.set_state()) and get data from the proxy array (await state.get_data()) in this called function) I get an error:
```File "/home/tspaul/Документы/Кристина_Маникюр_бот/virtualenv/lib/python3.11/site-packages/rodi/__init__.py", line 721, in get
    raise CannotResolveTypeException(desired_type)
rodi.CannotResolveTypeException: Unable to resolve the type '<class 'aiogram.dispatcher.storage.FSMContext'>'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tspaul/Документы/Кристина_Маникюр_бот/virtualenv/lib/python3.11/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tspaul/Документы/Кристина_Маникюр_бот/virtualenv/lib/python3.11/site-packages/apscheduler_di/_binding.py", line 102, in wrapper
    return await func(*resolve_dependencies(services, func, **kwargs))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tspaul/Документы/Кристина_Маникюр_бот/virtualenv/lib/python3.11/site-packages/apscheduler_di/_binding.py", line 118, in resolve_dependencies
    raise UnableToResolveDependencyError(
apscheduler_di._binding.UnableToResolveDependencyError: Unable to resolve the dependency: Instance of state argument found neither in apscheduler-di context nor in kwargs argument```

**Comment by tsy-pavel** [comment]
My code:

```async def send_step5_text(bot: Bot, chat_id: int, state: FSMContext) -> None:
    await bot.send_message(
        chat_id,
        text=TEXTS['step5'], parse_mode='MarkdownV2', reply_markup=inline_.block_finish_keyboard
    )

    bot_scheduler.remove_job('1')
    await state.set_state(states_list.wait_start_block2.state)
    logger.info(f"\n{await state.get_state()}\n{await state.get_data()}\n{'-'*100}\n")



async def send_video_1_8(callback: CallbackQuery, state: FSMContext) -> None:
    await state.set_state(states_list.wait_watch_1_8_videos.state)

    await callback.message.answer(text=GROUP_CAPTIONS['chapters'][1], parse_mode="MarkdownV2")

    for i in range(1, 9):
        await callback.message.answer_video(
            video=FILES_ID[i][0], protect_content=True, caption=FILES_ID[i][1]
        )

    await db.update_data(
        table_name='study_progress',
        update_fields='study_part',
        new_values='Блок 1',
        where_fields='user_id',
        where_fields_values=callback.message.chat.id
    )
    bot_scheduler.ctx.add_instance(state, FSMContext)
    try:
        bot_scheduler.add_job(
            send_step5_text,
            trigger='interval',
            seconds=TIMEOUT[1],
            id='1',
            kwargs={'chat_id': callback.message.chat.id}
        )
    except ConflictingIdError:
        pass
```

**Comment by tsy-pavel** [comment]
My solution:

```
bot = Bot(token=TOKEN)

storage = RedisStorage2(db=1, prefix='bot_fsm')
dp = Dispatcher(bot, storage=storage)

jobstores = {
    'default': RedisJobStore(db=2, host='localhost', port=6379)
}    

bot_scheduler = AsyncIOScheduler(timezone="Europe/Prague", jobstores=jobstores)
bot_scheduler = ContextSchedulerDecorator(AsyncIOScheduler(timezone="Europe/Prague", jobstores=jobstores))
bot_scheduler.ctx.add_instance(bot, Bot)
bot_scheduler.ctx.add_instance(storage, RedisStorage2)
```

and in handler:

```
async def send_step5_text(bot: Bot, chat_id: int, storage: RedisStorage2) -> None:
    await bot.send_message(
        chat_id,
        text=TEXTS['step5'], parse_mode='MarkdownV2', reply_markup=inline_.block_finish_keyboard
    )

    bot_scheduler.remove_job('3')
    
    await storage.set_state(chat=chat_id, state=states_list.wait_start_block2.state)
    logger.info(f"\n{await storage.get_state(chat=chat_id)}\n{await storage.get_data(chat=chat_id)}\n{'-'*100}\n")
```
